baseURL = 'https://clovereny.es'
languageCode = 'es-ES'
title = 'Clovereny - Materiales Cer치micos y Filtros Industriales'

[params]
  description = 'Especialistas en materiales cer치micos refractarios, filtros de cer치mica y componentes industriales de alta calidad'
  geo = 'es'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Espuma Cer치mica SiC"
    url = "/espuma-ceramica-sic/page-2/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/blog/page-24/"
    weight = 30 